import Foundation

/// The local user's profile. Stored on device only; never uploaded anywhere.
struct Profile: Codable, Equatable, Sendable {
    var displayName: String = ""
    var bio: String = ""
    var interests: [Interest] = []

    var isComplete: Bool { !displayName.trimmed().isEmpty && interests.count >= 1 }

    /// The subset we are willing to hand to a confirmed partner. Same shape as
    /// the full profile today, but going through one explicit type means we
    /// never accidentally widen what gets sent.
    var shareable: SharedProfile {
        SharedProfile(displayName: displayName.trimmed(), bio: bio.trimmed(), interests: interests)
    }
}

/// What actually crosses the wire, and only to a confirmed partner.
struct SharedProfile: Codable, Equatable, Hashable, Sendable {
    var displayName: String
    var bio: String
    var interests: [Interest]
}

/// One grounded thing two profiles genuinely share.
struct SharedHighlight: Codable, Equatable, Hashable, Identifiable, Sendable {
    var id: String { interestID }
    let interestID: String
    /// Human sentence, e.g. "You both play jazz piano."
    let statement: String
    /// The exact entry from each profile that supports the claim. Evidence, so
    /// nothing is asserted that isn't in both profiles.
    let yourEntry: String
    let theirEntry: String
    /// 2 = specific interest, 1 = broad category.
    let specificity: Int
}

/// The agreed result of a connection. Generated by exactly one participant and
/// shared, so both phones show the same thing.
struct ConnectionInsight: Codable, Equatable, Hashable, Sendable {
    var highlights: [SharedHighlight]
    var opener: String
    /// How the opener was produced. Surfaced in the UI — a template is never
    /// presented as an AI result.
    var openerSource: OpenerSource

    enum OpenerSource: String, Codable, Sendable {
        case onDeviceModel      // Apple Foundation Models, on device
        case fallbackTemplate   // deterministic, no model involved

        var label: String {
            switch self {
            case .onDeviceModel: return "Written on device by Apple Intelligence"
            case .fallbackTemplate: return "Suggested question"
            }
        }
    }
}

/// A saved connection. Local only.
struct SavedConnection: Codable, Equatable, Identifiable, Sendable {
    var id: UUID = UUID()
    var partnerName: String
    var partnerBio: String
    var metOn: Date
    var roomName: String
    var insight: ConnectionInsight
    /// How the two phones were paired. A manual pick is recorded honestly and is
    /// NOT counted as a hardware-detected bump.
    var pairingEvidence: PairingEvidence

    enum PairingEvidence: String, Codable, Sendable {
        case motionOnly
        case motionAndUWB
        case manualSelection

        var label: String {
            switch self {
            case .motionOnly: return "Matched by motion"
            case .motionAndUWB: return "Matched by motion + UWB"
            case .manualSelection: return "Picked manually"
            }
        }
    }
}
